### ISSUE TITLE
single quotes are producing `Error: Unknown line indicator` errors

### ISSUE THREAD

**Issue by faceyspacey** [slm-lang/slm#50]
For example:
```
.content
  p
    ' foo bar
```

Here's the trace:
```
WARNING in ./app/assets/angular/policy/trading_policy/en.tmpl.html.slim
Module build failed: Error: Unknown line indicator
  /Users/jamesgillmore/codementor/remitano/p2p-frontend/app/assets/angular/policy/trading_policy/en.tmpl.html.slim, Line 4, Column 5
      ' foo bar
      ^

    at Parser.p._syntaxError (/Users/jamesgillmore/codementor/remitano/p2p-frontend/node_modules/slm/lib/parser.js:691:9)
    at Parser.p._parseLineIndicators (/Users/jamesgillmore/codementor/remitano/p2p-frontend/node_modules/slm/lib/parser.js:338:10)
    at Parser.p._parseLine (/Users/jamesgillmore/codementor/remitano/p2p-frontend/node_modules/slm/lib/parser.js:189:8)
    at Parser.p.exec (/Users/jamesgillmore/codementor/remitano/p2p-frontend/node_modules/slm/lib/parser.js:125:10)
    at Engine.p.exec (/Users/jamesgillmore/codementor/remitano/p2p-frontend/node_modules/slm/lib/engine.js:14:26)
    at Template.p.src (/Users/jamesgillmore/codementor/remitano/p2p-frontend/node_modules/slm/lib/template.js:107:18)
    at Template.p.exec (/Users/jamesgillmore/codementor/remitano/p2p-frontend/node_modules/slm/lib/template.js:99:31)
    at Template.p.compile (/Users/jamesgillmore/codementor/remitano/p2p-frontend/node_modules/slm/lib/template.js:76:17)
    at Object.module.exports (/Users/jamesgillmore/codementor/remitano/p2p-frontend/node_modules/slm-loader/index.js:16:22)
 @ ./app/assets/angular \.slim$
 @ ./app/assets/packs/application.js
 @ multi (webpack)-dev-server/client?http://localhost:3035 webpack/hot/dev-server ./app/assets/packs/application.js
```

Here's an example of the error in running in the browser on runkit: 
https://runkit.com/faceyspacey/5abf6c4bb484d300124b5bfb

**Comment by faceyspacey** [comment]
closing, as I found the issue in one of the parsing regexes and opened a PR:

https://github.com/slm-lang/slm/pull/51
